Vagrant::Config.run do |config|

  config.vm.box = "raring"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/20131001/raring-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.provision :shell, :inline => "sudo apt-get update && sudo apt-get install puppet -y"

 config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "./puppet/"
    puppet.manifest_file  = "manifests/site.pp"
    puppet.module_path = "./puppet/modules/"
  end

  config.vm.forward_port 80, 8080

  (49000..49900).each do |port|
    config.vm.forward_port port, port
  end

end


Vagrant.configure("2") do |config|
  config.vm.synced_folder "./puppet/", "/srv/dev-puppet"
end
